<a href="https://colab.research.google.com/github/Nazaruk-Anton/COVID-19-Genome-Sequencing-Analysis-and-Bit-Score-Prediction/blob/main/Part_4_Predicting_Bit_Scores_of_Sequences.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

To find the genome sequences that are most closely related to the reference genome (NC_045512.2 Wuhan seafood market pneumonia virus isolate Wuhan-Hu-1) and potentially identify a subsequence to target with a combative drug, we can use the bit scores as a measure of similarity.

Higher bit scores indicate a stronger similarity, suggesting that sequences with higher scores are more closely related to the reference genome. On the other hand, lower bit scores indicate lower similarity, implying less relatedness.

To leverage this information, we can focus on the sequences with the highest bit scores. These sequences are more likely to share a closer evolutionary relationship with the reference genome and are therefore potential candidates for further analysis and drug targeting.

Conversely, sequences with the lowest bit scores might represent more divergent or distinct strains, and targeting them with a combative drug may be less effective.

In [1]:
### Loading in data

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression

In [2]:
### Reading in data. We'll store our data in dataframe called 'df'.

df = pd.read_csv('/content/Alignment-HitTable.csv', header = None)
df.columns = ['query acc.verr', 'subject acc.ver', '% identity', 'alignment length', 'mismatches', 
             'gap opens', 'q. start', 'q. end', 's. start', 's. end', 'evalue', 'bit score']
df.head()

,query acc.verr,subject acc.ver,% identity,alignment length,mismatches,gap opens,q. start,q. end,s. start,s. end,evalue,bit score
0,MN997409.1,MN997409.1,100.00,29882,0,0,1,29882,1,29882,0.0,55182
1,MN997409.1,MT020881.1,99.99,29882,3,0,1,29882,1,29882,0.0,55166
2,MN997409.1,MT020880.1,99.99,29882,3,0,1,29882,1,29882,0.0,55166
3,MN997409.1,MN985325.1,99.99,29882,3,0,1,29882,1,29882,0.0,55166
4,MN997409.1,MN975262.1,99.99,29882,3,0,1,29882,1,29882,0.0,55166

In [3]:
## In this final notebook, we'll be predicting 'bit_score' from some of the columns in the data.
## Create a feature dataframe called 'X' with the columns: ['% identity',  'mismatches', 'gap opens', 'q. start', 's. start'].
## Store the target 'y' with the bit scores.

X = df[['% identity',  'mismatches', 
             'gap opens', 'q. start', 's. start']]
y = df['bit score']

### Use the Standard Scaler from the sklearn.preprocessing library to normalize the data.
## Store the transformed X data in a variable called 'X_transformed'.
ss = StandardScaler()
X_transformed = ss.fit_transform(X)

In [4]:
## Predict the bit score by fitting a linear regression model. Store the predicted bit scores in
## a variable called 'lin_pred'. Get the score in a variable called 'lin_score'. 
## Store the linear regression coefficients in a variable called 'coef'.

linreg = LinearRegression()
linreg.fit(X_transformed, y)
score = linreg.score(X_transformed, y)
lin_pred = linreg.predict(X_transformed)
coef = linreg.coef_

In [5]:
lin_pred

array([49636.55233745, 49588.64767161, 49588.64767161, 49588.64767161,
       49588.64767161, 49559.15766986, 49573.46264729, 49573.46264729,
       49573.46264729, 49573.46264729, 49573.46264729, 49543.97264554,
       49543.97264554, 49558.57097193, 49558.57097193, 49555.92803009,
       49555.92803009, 49603.83269593, 49540.74300576, 49540.74300576,
       49525.55798144, 49525.55798144, 49525.55798144, 49525.55798144,
       49525.55798144, 49379.86020808, 49477.65331559, 49492.83833992,
       49753.08673984, 49463.34833817, 49540.74300576, 49477.65331559,
       49275.62914013, 49427.39905687, 49364.97919228, 49168.45112182,
       49347.15122611, 49144.83370168, 49362.04290147, 49666.32646219,
       49528.78762121, 49049.31771896, 49824.45490142, 49528.7551882 ,
       48792.44958797, 36498.1816252 , 33886.59064785, 20530.74441579,
        8046.27178069, 10757.14286689,  8028.89015196, 32019.62703583,
       17893.6270238 , -5388.20141405,  7722.01096679,  4631.63446961,
       17893.6270238 , -5388.20141405,  7722.01096679,  4631.63446961,
       17379.03158034, -5902.79685751,  7207.41552332,  3154.84873603,
       17849.15941791, -5840.94177097,  8783.19648399,  4631.63446961,
       17849.15941791, -5737.73434321,  8884.57200224,  4761.9495448 ,
       18021.456173  , -5173.78664593,  9147.24075365,  5461.033559  ,
       14167.74409448, -8800.14462478,  5837.90315418, -3132.87051989,
       17784.80760194, -5440.97992437,  8782.53263625,  5598.48904964,
       17999.22237005, -6981.03197423,  5448.43891694,  6418.90395101,
       17784.80760194, -5440.97992437,  8782.53263625,  5598.48904964,
       16992.42914135, -6006.00428528,  8682.47241113,  3022.18406797,
       17507.02458482, -5440.97992437,  9197.06785459,  4503.66898729,
       17750.62907399, -5558.48167001,  8613.16518863,  5376.90061213,
       17979.33815998, -5226.56515626,  8884.16694637,  5939.968755  ,
       17948.96811133,  6845.79272449,  2488.12736121, 17556.45420663,
       -4071.93193731, 10189.94796338,  2926.95515072, 16927.91347009,
       -7647.82206754,  7410.27812033,  3259.17340084, 17213.79982758,
       -5917.09117539,  8253.6428749 ,  4080.96611908, 17356.74300632,
       -5826.92650697,  8396.58605364,  4488.33808889, 17742.68958892,
       -5440.97992437,  8782.53263625,  5598.48904964, 18202.62095018,
       -5388.20141405,  8782.53263625,  5468.17397445, 18441.89767295,
       -5440.97992437,  8782.53263625,  4503.66898729, 17484.79078187,
       -5491.40884181,  9197.06785459,  4503.66898729, 17742.68958892,
       -5491.40884181,  8782.53263625,  5598.48904964, 17742.68958892,
       -7155.224624  ,  3264.92593684,  5598.48904964, 17942.81003915,
       -5300.68676307,  8012.80383792,  5538.42962203, 18443.11116475,
       -6029.41694512,  9398.36886858,  6352.24665621, 17728.39527104,
       -5505.70315969,  8754.14076112,  5376.90061213, 17728.39527104,
       -5558.48167001,  8627.26274588,  5376.90061213, 17728.39527104,
       -6734.73446733,  7884.5484983 ,  5637.53076251, 17814.16117829,
       -5472.71576276,  8713.02865313,  5409.33048863, 17842.74981404,
       -5637.67411809,  8727.51973163,  5725.4424264 , 17742.68958892,
       -5544.18735213,  8782.53263625,  5598.48904964, 17957.10435703,
       -5329.77258402,  8996.94740436,  5939.968755  , 17957.10435703,
       -5329.77258402,  8996.94740436,  5939.968755  , 17957.10435703,
       -5226.56515626,  8827.77671737,  5939.968755  , 17957.10435703,
       -5226.56515626,  8996.94740436,  5939.968755  , 17685.51231742,
       -4991.26641011,  8177.90022491,  5568.20492978, 17957.10435703,
       -5226.56515626,  8855.97183187,  5939.968755  , 17957.10435703,
       -4564.60124076,  8996.94740436,  5939.968755  , 17957.10435703,
       -5329.77258402,  8996.94740436,  5939.968755  , 17957.10435703,
       -5226.56515626,  8996.94740436,  5939.968755  , 17957.10435703,
       -5226.56515626,  8996.94740436,  5939.968755  , 17728.39527104,
       -5455.27424224,  8599.06763138,  5637.53076251, 17756.98390679,
       -5529.89303426,  8768.23831837,  5639.22624662, 17957.10435703,
       -5226.56515626,  8855.97183187,  5939.968755  , 17957.10435703,
       -5226.56515626,  8855.97183187,  5939.968755  , 17957.10435703,
       -5329.77258402,  8855.97183187,  5812.00327269, 17957.10435703,
       -5276.9940737 ,  8855.97183187,  5939.968755  , 17957.10435703,
       -5276.9940737 ,  8827.77671737,  5939.968755  , 17957.10435703,
       -5276.9940737 ,  8996.94740436,  5939.968755  , 17728.39527104,
       -5402.49573192,  8599.06763138,  5637.53076251, 17742.68958892,
       -5491.40884181,  8782.53263625,  5598.48904964])

By analyzing the bit scores, we can identify sequences with high similarity to the reference genome, which can help in tracing closely related genome sequences and potentially identifying a subsequence to target with a combative drug. However, it's important to note that further analysis, such as phylogenetic studies and experimental validation, would be necessary to confirm the findings and assess the suitability of a particular sequence as a drug target.